# Generated by Django 4.1.4 on 2023-08-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_comment_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='data',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
    ]
