# Generated by Django 4.1.4 on 2023-08-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_reseller',
            field=models.BooleanField(default=False, verbose_name='Cтатус реселлера'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_vip',
            field=models.BooleanField(default=False, verbose_name='Статус ViP'),
        ),
    ]
