# Generated by Django 4.1.4 on 2023-08-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_liqpaynotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cума')),
                ('fonds', models.CharField(choices=[('UAH', 'UAH'), ('USD', 'USD'), ('EUR', 'EUR')], default='UAH', max_length=5, verbose_name='Валюта')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Платiж',
                'verbose_name_plural': 'Платежi',
            },
        ),
        migrations.DeleteModel(
            name='LiqPayNotification',
        ),
    ]
