# Generated by Django 4.1.4 on 2023-08-22 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_payment_delete_liqpaynotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('created', 'Створений'), ('proccessing', 'В обробці'), ('completed', 'Виконаний'), ('failed', 'Відмовлено')], default='created', max_length=15, verbose_name='Статус'),
        ),
    ]
