# Generated by Django 4.1.4 on 2023-08-24 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_payment_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_reseller',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_vip',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_status',
            field=models.CharField(choices=[('regular', 'Для звичайних клiентiв.'), ('reseller', 'Для reseller клiентiв.'), ('vip', 'Для ViP клiентiв.')], default='regular', max_length=15, verbose_name='Cтатус профiля'),
        ),
    ]
