# Generated by Django 4.1.4 on 2023-08-24 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_user_is_reseller_remove_user_is_vip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_status',
            field=models.CharField(choices=[('regular', 'Звичайний клiент.'), ('reseller', 'Reseller клiент.'), ('vip', 'ViP клiентiв.')], default='regular', max_length=15, verbose_name='Cтатус профiля'),
        ),
    ]
