# Generated by Django 4.1.4 on 2023-08-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_profile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='fonds',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR')], default='USD', max_length=5, verbose_name='Валюта'),
        ),
    ]
