# Generated by Django 4.1.4 on 2023-08-06 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='Назва')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=32, verbose_name='Послуга')),
                ('min_count', models.IntegerField(verbose_name='Мінімальна кількість')),
                ('price', models.IntegerField(verbose_name='Ціна')),
                ('social_network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.socialnetwork')),
            ],
        ),
    ]
