# Generated by Django 4.1.4 on 2023-08-14 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=32, verbose_name='Заголовок')),
                ('link_1', models.CharField(max_length=64, verbose_name='Посилання 1')),
                ('link_2', models.CharField(max_length=64, verbose_name='Посилання 2')),
                ('link_3', models.CharField(max_length=64, verbose_name='Посилання 3')),
                ('link_4', models.CharField(max_length=64, verbose_name='Посилання 4')),
                ('link_5', models.CharField(max_length=64, verbose_name='Посилання 5')),
            ],
            options={
                'verbose_name': 'Информація',
                'verbose_name_plural': 'Информація',
            },
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Послуга', 'verbose_name_plural': 'Послуги'},
        ),
        migrations.AlterModelOptions(
            name='socialnetwork',
            options={'verbose_name': 'Соціальна мережа', 'verbose_name_plural': 'Соціальні мережі'},
        ),
        migrations.RemoveField(
            model_name='service',
            name='price',
        ),
        migrations.AddField(
            model_name='service',
            name='service_logo',
            field=models.ImageField(null=True, upload_to='service_logos', verbose_name='Лого'),
        ),
        migrations.AddField(
            model_name='socialnetwork',
            name='description',
            field=models.CharField(default='', max_length=80, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='socialnetwork',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активна категорія'),
        ),
        migrations.AddField(
            model_name='socialnetwork',
            name='logo',
            field=models.ImageField(default=None, upload_to='logos', verbose_name='Лого'),
        ),
        migrations.AlterField(
            model_name='service',
            name='min_count',
            field=models.PositiveIntegerField(verbose_name='Мінімальна кількість'),
        ),
        migrations.AlterField(
            model_name='service',
            name='social_network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.socialnetwork', verbose_name='Соціальна мережа'),
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=32, verbose_name='Вид')),
                ('price_per_1', models.PositiveIntegerField(verbose_name='Ціна за одиницю')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service', verbose_name='Тип послуги')),
            ],
            options={
                'verbose_name': 'Тип послуги',
                'verbose_name_plural': 'Типи послуги',
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=32, verbose_name='Назва')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='Кількість')),
                ('url', models.URLField(blank=True, default='', verbose_name='Посилання')),
                ('status', models.CharField(choices=[(0, 'Неактивований'), (1, 'В обробці'), (2, 'Виконаний'), (3, 'Відмовлено')], default=0, max_length=12, verbose_name='Статус')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Виконаний')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Клієнт')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='services.service', verbose_name='Послуга')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоди',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(verbose_name='Кількість')),
                ('url', models.URLField(blank=True, default='', verbose_name='Посилання')),
                ('price', models.PositiveIntegerField(blank=True, verbose_name='Ціна')),
                ('status', models.CharField(choices=[(0, 'Створений'), (1, 'В обробці'), (2, 'Виконаний'), (3, 'Відмовлено')], default=0, max_length=12, verbose_name='Статус')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Виконаний')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Клієнт')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='services.service', verbose_name='Послуга')),
                ('service_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='services.servicetype', verbose_name='Тип послуги')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
            },
        ),
    ]
