# Generated by Django 4.1.4 on 2023-08-14 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_footer_alter_service_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('0', 'Створений'), ('1', 'В обробці'), ('2', 'Виконаний'), ('3', 'Відмовлено')], default='0', max_length=12, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='status',
            field=models.CharField(choices=[('0', 'Неактивований'), ('1', 'В обробці'), ('2', 'Виконаний'), ('3', 'Відмовлено')], default='0', max_length=12, verbose_name='Статус'),
        ),
    ]
