# Generated by Django 4.1.4 on 2023-08-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_order_status_alter_promocode_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='link_2',
            field=models.CharField(blank=True, max_length=64, verbose_name='Посилання 2'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='link_3',
            field=models.CharField(blank=True, max_length=64, verbose_name='Посилання 3'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='link_4',
            field=models.CharField(blank=True, max_length=64, verbose_name='Посилання 4'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='link_5',
            field=models.CharField(blank=True, max_length=64, verbose_name='Посилання 5'),
        ),
    ]
