# Generated by Django 4.1.4 on 2023-08-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_footer_link_2_alter_footer_link_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='name_1',
            field=models.CharField(default='', max_length=64, verbose_name='Назва 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footer',
            name='name_2',
            field=models.CharField(default='', max_length=64, verbose_name='Назва 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footer',
            name='name_3',
            field=models.CharField(blank=True, max_length=64, verbose_name='Назва 3'),
        ),
        migrations.AddField(
            model_name='footer',
            name='name_4',
            field=models.CharField(blank=True, max_length=64, verbose_name='Назва 4'),
        ),
        migrations.AddField(
            model_name='footer',
            name='name_5',
            field=models.CharField(blank=True, max_length=64, verbose_name='Назва 5'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='link_2',
            field=models.CharField(max_length=64, verbose_name='Посилання 2'),
        ),
    ]
