# Generated by Django 4.1.4 on 2023-08-17 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_footer_name_1_footer_name_2_footer_name_3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='servicetype',
            name='price_per_1',
        ),
        migrations.AddField(
            model_name='servicetype',
            name='price_per_1000',
            field=models.PositiveIntegerField(default=0, verbose_name='Ціна за тисячу'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='self_to',
            field=models.IntegerField(choices=[(0, 'WiQ'), (1, 'GlobalSmm')], default=0, verbose_name='Вiдношення до сервiсу'),
        ),
        migrations.AlterField(
            model_name='order',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='services.servicetype', verbose_name='Тип послуги'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Створений'), (1, 'В обробці'), (2, 'Виконаний'), (3, 'Відмовлено')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_logo',
            field=models.ImageField(default=None, upload_to='service_logos', verbose_name='Лого'),
        ),
        migrations.DeleteModel(
            name='PromoCode',
        ),
    ]
