# Generated by Django 4.1.4 on 2023-08-18 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_remove_order_is_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='service_id',
            field=models.IntegerField(default=0, verbose_name='Код послуги (id)'),
        ),
    ]
