# Generated by Django 4.1.4 on 2023-08-18 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_servicetype_service_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='link_1',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='link_2',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='link_3',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='link_4',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='link_5',
        ),
    ]
