# Generated by Django 4.1.4 on 2023-08-18 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_alter_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, max_length=32, verbose_name='Номер заказу'),
        ),
    ]
