# Generated by Django 4.1.4 on 2023-08-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Створений. Ще не оброблений заказ.'), (1, 'В обробці. Заказ перебуває на обробцi.'), (2, 'Виконаний. Заказ повнiстю виконаний.'), (3, 'Відмовлено. Недостатньо коштiв на балансi сервicу.'), (4, 'Відмовлено. Не вірний id послуги.'), (5, 'Відмовлено. Невiдома помилка.')], default=0, verbose_name='Статус'),
        ),
    ]
