# Generated by Django 4.1.4 on 2023-08-23 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicetype',
            name='self_to',
        ),
        migrations.AddField(
            model_name='servicetype',
            name='self_to_client',
            field=models.CharField(choices=[('regular', 'Для звичайних клiентiв.'), ('reseller', 'Для reseller клiентiв.'), ('vip', 'Для ViP клiентiв.')], default='regular', max_length=15, verbose_name='Вiдношення до типу клiентiв'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='self_to_service',
            field=models.CharField(choices=[('wiq', 'WiQ'), ('globalsmm', 'GlobalSmm')], default='wiq', max_length=15, verbose_name='Вiдношення до сервiсу'),
        ),
    ]
