# Generated by Django 4.1.4 on 2023-08-24 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_remove_servicetype_self_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='data',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='self_to_client',
            field=models.CharField(choices=[('regular', 'Звичайний клiент.'), ('reseller', 'Reseller клiент.'), ('vip', 'ViP клiентiв.')], default='regular', max_length=15, verbose_name='Вiдношення до типу клiентiв'),
        ),
    ]
