# Generated by Django 4.1.4 on 2023-08-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_order_data_alter_servicetype_self_to_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetype',
            name='price_per_1000',
            field=models.PositiveIntegerField(default=0, verbose_name='Ціна за тисячу ($)'),
        ),
    ]
