# Generated by Django 4.1.4 on 2023-08-06 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thema', models.CharField(max_length=32, verbose_name='Тема')),
                ('question', models.CharField(max_length=512, verbose_name='Опис')),
                ('notes', models.CharField(max_length=64, verbose_name='Примітки')),
                ('report', models.ImageField(blank=True, null=True, upload_to='reports', verbose_name='Cкріншот')),
                ('answer', models.CharField(max_length=128)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
