# Generated by Django 4.1.4 on 2023-08-06 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportmail',
            options={'verbose_name': 'Лист підтримки', 'verbose_name_plural': 'Листи підтримки'},
        ),
        migrations.AlterField(
            model_name='supportmail',
            name='answer',
            field=models.CharField(max_length=128, verbose_name='Відповідь'),
        ),
        migrations.AlterField(
            model_name='supportmail',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач'),
        ),
    ]
