# Generated by Django 4.1.4 on 2023-08-11 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_alter_supportmail_options_alter_supportmail_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportmail',
            name='data',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата'),
        ),
    ]
