# Generated by Django 4.1.4 on 2023-08-15 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_supportmail_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportmail',
            name='answer',
            field=models.CharField(blank=True, max_length=128, verbose_name='Відповідь'),
        ),
        migrations.AlterField(
            model_name='supportmail',
            name='data',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='supportmail',
            name='report',
            field=models.ImageField(blank=True, upload_to='reports', verbose_name='Cкріншот'),
        ),
    ]
