# Generated by Django 4.1.4 on 2023-08-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=32, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=512, verbose_name='Опис')),
            ],
        ),
    ]
