# Generated by Django 4.1.4 on 2023-08-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='short_description',
            field=models.CharField(default=0, max_length=512, verbose_name='Короткий опис'),
            preserve_default=False,
        ),
    ]
